Added conditions if: always() and continue-on-error: true to the download action. Modified syntax for error message and exit code in step: Build executable. Modification under test.

diff --git a/.github/workflows/hello_world_m111.yml b/.github/workflows/hello_world_m111.yml
--- a/.github/workflows/hello_world_m111.yml
+++ b/.github/workflows/hello_world_m111.yml
@@ -91,8 +91,7 @@ jobs:
             if [ $? -eq 0 ]; then
                echo "Build succeeded"
             else 
-               echo "Build failed"
-               exit 1
+               echo "::error::Build failed for context hello_world.${{ matrix.build.type }}+${{ matrix.target.type }} with toolchain ${{ matrix.compiler.name }} "  && exit 1
             fi
 
       # Upload build log
@@ -147,6 +146,8 @@ jobs:
       # Download previous generated logs
       - name: Download ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
         uses: actions/download-artifact@v4
+        if: always()
+        continue-on-error: true        
         with:
           name: ${{ matrix.target.type }}.${{ matrix.compiler.name }}.${{ matrix.build.type }}.build.log
           path: tmp
